name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        host: ${{ env.HOST }}
        USERNAME: ${{ env.USERNAME }}
        PORT: ${{ env.PORT }}
        KEY: ${{ env.SSHKEY }}
      with:
        source: "."
        target: "/var/www/vhosts/dinorank.com/prueba-cd"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
